name: DNI Bot CI Build

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

env:
  # docker-compose.yml file required environment variables for just build
  BOT_DB_LOCAL_PORT: 3306

jobs:
  corporallancot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Node Dependencies
      working-directory: ./
      run: |
        set -x;
        npm set progress=false;
        npm install --no-progress;
    - name: Lint
      working-directory: ./
      run: npm run lint
    - name: Tests
      working-directory: ./
      run: npm run test
    - name: Build Docker Images
      working-directory: ./
      run: |
          set -x;
          docker-compose build;
